name: Lint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check illegal format
        id: check_format
        uses: psf/black@stable
        with:
          src: "./src"
          options: "--check --verbose"
      - name: exit if no problem format
        run: exit_with_success
        if: steps.check_format.outcome == "success"
      - name: set branch suffix
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV         
      - name: create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c fix_${{github.head_ref}}_${{ env.CURRENT_DATETIME }}
          git push -u origin fix_${{github.head_ref}}_${{ env.CURRENT_DATETIME }}
      - name: apply black
        uses: psf/black@stable
        with:
          src: "./src"
      - name: commit fix format
        uses: EndBug/add-and-commit@v7
        with:
          branch: fix_${{github.head_ref}}_${{ env.CURRENT_DATETIME }}
          message: fix format
      - name: create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: fix_${{github.head_ref}}_${{ env.CURRENT_DATETIME }}
          destination_branch: ${{github.head_ref}}
          pr_title: fix format ${{ env.PR_TITLE }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

